### ISSUE TITLE
[Info request] How to compile

### ISSUE THREAD

**Issue by ItachiSan** [haskellcamargo/skype-unofficial-client#1]
Hello,
I just wanted to know where/which are the sources used for compiling the binaries, as I'm not that practical of node.js and I wanted to understand better how it works.

**Comment by onlurking** [comment]
The project is built top on [node-webkit](https://github.com/nwjs/nw.js), the application just open the [web version of skype](https://web.skype.com/en/) like a web browser(rendering with webkit), the node application itself just reads the [package.json](https://github.com/haskellcamargo/skype-unofficial-client/blob/master/bin/linux_x64/package.json).

**Comment by onlurking** [comment]
If you are really interest in node.js, i would recommend you to read the source of Quildreen's [Raven](https://github.com/robotlolita/raven), which is a far more complex project than ours.

**Comment by alex-eri** [comment]
What about sources?

**Comment by onlurking** [comment]
@alex-eri [package.json](https://github.com/haskellcamargo/skype-unofficial-client/blob/master/bin/linux_x64/package.json), yes, really.
It just open https://web.skype.com/en/ on the windows, rendering with node-webkit.
