### ISSUE TITLE
Ghost session

### ISSUE THREAD

**Issue by ghost** [haskellcamargo/skype-unofficial-client#12]
I got a ghost open session after closing all `skype-unofficial-client` instances. It was listed simply as `skype()` using `/showplaces`. Perhaps a Skype web client but, but there's no way for me to know.

Anyway, the repo consisting mainly of binaries and the lack of comments from the devs is too shady. I'm staying away from this project for good. Good luck.

**Comment by Kuchiriel** [comment]
@kehugter Ok, stay away for good. Good Luck.

**Comment by Kuchiriel** [comment]
@kehugter Well, before you get away, take a look at the /src dir, the binary just render that files.
If u wanna build your own binary out of the src its very simple.

https://github.com/nwjs/nw.js/wiki/how-to-package-and-distribute-your-apps

If u wanna help, or do constructive criticism reopen the issue.
