### ISSUE TITLE
Windows ?

### ISSUE THREAD

**Issue by unixfox** [haskellcamargo/skype-unofficial-client#15]
Is it possible to port the app on Windows ?

**Comment by haskellcamargo** [comment]
Yeah, it easily is. I'll do it soon!

**Comment by unixfox** [comment]
:+1:

**Comment by tcmal** [comment]
@unixfox I think you're missing the point: The windows skype client has all the features. This linux port is of the web version because the skype for linux client is rubbish and hasn't been updated in ages. You can just use the official one.

**Comment by unixfox** [comment]
@OscarOrSomething I know but I think that porting the application to Windows isn't difficult due the technology behind this application so I propose to the developer if he wishes.

**Comment by Kuchiriel** [comment]
Yeah, its possible to port to Mac OS X even. If @haskellcamargo agree, i will do a cross-platform make script.
