### ISSUE TITLE
Open Links in the default browser instead of the program itself.

### ISSUE THREAD

**Issue by weini37** [haskellcamargo/skype-unofficial-client#16]
You basically could decide between two things:
- Images sent directly from skype will be shown in a popup (like it's now)
- Every other link will be opened in the default web browser

Why?

For example the current program doesn't support playing raw mp4 files and so on.

Since it's no use creating a fully functional webbrowser for everything - why not just simply add the function that we open a the default webbrowse with that link?

**Comment by Kuchiriel** [comment]
@weini37 Simple function will be added, hold on.

**Comment by Kuchiriel** [comment]
@weini37 Try it now. Here works fine. Anything reopen the issue.
