### ISSUE TITLE
Just a wrapper (webview) of https://web.skype.com right?

### ISSUE THREAD

**Issue by ngonhan2k5** [haskellcamargo/skype-unofficial-client#17]
Very surprised when catching this project, thought that you guys doing amazing things is implement skype and build a beautifull UI, and eagerly give some corporating.
But soon get disappointed because this just a wrapper of https://web.skype.com.
Therefore we can do anything with all these issues here if it's out of wrapper scope.

Why not any comment in Readme.md?

Thank for a good wrapper anyway.

**Comment by Kuchiriel** [comment]
@ngonhan2k5 "Built on top of node-webkit" is a relevant comment in Readme.md, you can figure it out that this is a wrapper for web client.
