### ISSUE TITLE
Ubuntu tray icon

### ISSUE THREAD

**Issue by andreyluiz** [haskellcamargo/skype-unofficial-client#18]
Skype do not appear in the tray icon. And do not execute in background. Is there a way to do this?

Thank's. :+1:

**Comment by iagocaldeira** [comment]
+1

**Comment by sagarguhe** [comment]
+1

**Comment by nemanjan00** [comment]
+1

**Comment by iagocaldeira** [comment]
some days ago it returned to work

**Comment by iagocaldeira** [comment]
idk what i did :eyes:

**Comment by andreyluiz** [comment]
@haskellcamargo, some tip?

**Comment by haskellcamargo** [comment]
@Kuchiriel, @onlurking, do we have some news about?

**Comment by Kuchiriel** [comment]
@haskellcamargo Yeah, its simple, i will do it today.

**Comment by andreyluiz** [comment]
Ty

**Comment by Kuchiriel** [comment]
@andreyluiz I already did the tray feature, but something is wrong with the binary. I guess is needed to rebuild and update the binary, but i dont know if it works in others system the way it is now, if u could test it and feedback me. Doing the command "nw ." in the /src folder, runs app with tray feature working.

**Comment by bilelmoussaoui** [comment]
If you guys implement this, please don't hardcode the icons (put them on /usr/share/icons/hicolor...)

**Comment by Kuchiriel** [comment]
@bil-elmoussaoui Open an issue about your suggestions with detailed instructions, and we will do a enhancement tag, and try to implement. Thanks for the feedback.

**Comment by andreyluiz** [comment]
I'll test it out and feedback you, guys.

**Comment by Kuchiriel** [comment]
Ty, @andreyluiz

**Comment by LawrenceBobrov** [comment]
I have recently installed on Ubuntu and this feature is not working! Fix, please, we miss it too much!

**Comment by Kuchiriel** [comment]
@haskellcamargo

**Comment by andreyluiz** [comment]
Sorry for the delay.

Tested with both the src and "(m/b)aked" application and the tray icon does not work.

**Comment by trollfred** [comment]
+1 the whole thing is useless without this feature

**Comment by gwemmie** [comment]
+1, doesn't work for me, either (on Arch Linux). And I have 2 suggestions:
-Can we please make sure the tray icon works on more distros than JUST Ubuntu (I don't know if you've already done that; just knee-jerk replying to this issue's title), by employing the same free desktop standards that most open-source programs do?
-Can the tray icon also include some feature where the icon permanently changes in some way to let me know there are new messages, as most messaging apps do? Maybe an unread count like in the original borked Skype Linux client.

For those of you who want this now, we can use Alltray until this gets fully implemented. I'm currently looking up ways to maybe make my own tray icon that grabs notifications and changes its icon based on said notifications, and I think it'd be doable with just scripting thanks to this page: http://askubuntu.com/questions/105566/is-there-a-way-to-view-notification-history

**Comment by LawrenceBobrov** [comment]
@Jimi-James 
Could you please explain in more details how to configure Alltray?
It does not work out of box for me..

**Comment by gwemmie** [comment]
You just install it and pass another program in as its argument, maybe with a -H to make it minimize on launch or any other option you might like in its documentation.

If you're not seeing the tray icon that it's supposed to make, that could be a number of things that I'm not qualified to help with. AFAIK is that it works for me in XFCE's system tray. There are other programs that do what alltray does, and if you're on KDE, I'm pretty sure alltray is not the best choice (don't remember which one was).

**Comment by LawrenceBobrov** [comment]
Thanks @Jimi-James !
Actually, I did this way: 

> sudo add-apt-repository ppa:jconti/recent-notifications
> sudo apt-get update
> sudo apt-get install indicator-notifications

I have restarted unity and it started collecting notifications. However, seems that this packages has not installed new binaries.
Could you please explain which service/application should I restart and with what parameters?

**Comment by gwemmie** [comment]
Oh, I didn't realize you were having trouble with notifications. alltray has nothing to do with notifications. All it does is give a window a tray icon that it can minimize to. It should be its own package, and maybe it also requires a PPA?

**Comment by Kuchiriel** [comment]
To give some clearance for Arch Linux users and JS devs.

https://wiki.archlinux.org/index.php/Desktop_notifications

**JavaScript**
- Dependencies: libnotify, gjs (works also with seed)

```
 hello_world.js
#!/usr/bin/gjs
const Notify = imports.gi.Notify;
Notify.init ("Hello world");
var Hello=new Notify.Notification ({summary: "Hello world!",
                                    body: "This is an example notification.",
                                    "icon-name": "dialog-information"});
Hello.show ();
```
