### ISSUE TITLE
Emojis are not playable

### ISSUE THREAD

**Issue by sagarguhe** [haskellcamargo/skype-unofficial-client#19]
Hi, I am using this skype client, first of all Great Job you have done for linux people... But I don't know why the emojis are not getting played. When I click on them to play they turn into a black rectangle and won't turn back to their initial stage... Same issue when I am in the process of selecting emojis from the menu.

**Comment by Kuchiriel** [comment]
Could you print it please?

**Comment by DaniellMesquita** [comment]
@sagarguhe.
