### ISSUE TITLE
Add to description additional info

### ISSUE THREAD

**Issue by Yanpas** [haskellcamargo/skype-unofficial-client#2]
- Why Skype for web better than Linux's. (Because it has group video calls?)
- There is easier way to install this web app if you have chromium based browser - open web.skype.com. Press Menu - More - Add to Desktop (I don't remember exactly namings of menu items coz do not use english locale) ,  tick "open in individual windows" - and voila, you have skype in your app menu and on the desktop.

**Comment by Kuchiriel** [comment]
Linux Skype app is ugly, a lot, i really dont like it. Not all people like using chrome, and the one who likes it, may not like have to open the RAM eater browser just to use skype. There is a lot of reasons why someone would like to use that app, there is no point to don't make it happen and improve it.
