### ISSUE TITLE
"Please update your browser to start using Skype" 

### ISSUE THREAD

**Issue by Similacrest** [haskellcamargo/skype-unofficial-client#20]
The site returns "Please update your browser to start using Skype." message.
![screenshot_2015-12-02_12-08-25](https://cloud.githubusercontent.com/assets/2362022/11528123/79274322-98ed-11e5-9412-fc7a78896982.png)

Maybe you need to update Webkit or change the UserAgent.

**Comment by koroshiya** [comment]
This error is occurring for me in Chrome and Firefox as well, both fully up to date.
Perhaps Microsoft botched the latest update to web.skype?

**Comment by Similacrest** [comment]
Works for me in chromium 46 & firefox 42, but not in node-webkit 1.2.1 here, which uses chromium 41. Updating it to 1.2.3 didn't help.
JS console of NW outputs "Uncaught ReferenceError: require is not defined", might be related

**Comment by Similacrest** [comment]
In node webkit alpha (v13) with the  chromium 46 not working too

**Comment by CirnoT** [comment]
https://github.com/haskellcamargo/skype-unofficial-client/pull/23

**Comment by ghanshyamsoni245** [comment]
<b>==> In Mozilla Firefox  :</b>

Weeks passed and this is still not fixed. For all of you that need a workaround, here it is:

You just need to change your "User Agent" that your browser presents to a webserver.

For any Firefox flavor like Debian's Icedove you need to go to <b>about:config</b>
(you will see a warning, you need to promise by clicking "I'll be careful, I promise!" button)

Find <b>general.useragent.override</b> and if it is not there, you need to add it:
Right-click, New, String, enter name: <b>general.useragent.override</b>

Then enter as it's value:
<b>Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko</b>
to pretend that your browser is something that it's not: a broken browser for a broken skype.

You can achieve same result by using browser extension that changes User-Agent.
