### ISSUE TITLE
Use StartupWMClass 

### ISSUE THREAD

**Issue by bilelmoussaoui** [haskellcamargo/skype-unofficial-client#29]
I don't know if you can set that using NodeJS , but the desktop application should have the same name as the StartupWMClass.

![capture d ecran de 2016-01-24 16-59-34](https://cloud.githubusercontent.com/assets/7660997/12537303/de61f046-c2bb-11e5-9946-597e86581353.png)
The popover of the application name shows Chromuim-browser instead of Skype (due to the missing StartupWMClass)

**Comment by Kuchiriel** [comment]
Dude, it seems to be an issue of your desktop environment. In my DE it pops up the current URL location title.

Example: 
Before you sign in:
 "Sign in your Skype account"

After you did it, it pops up:
 "Skype"

**Comment by bilelmoussaoui** [comment]
Yeah, i just found the issue on Node.js repo and it's only happens on Gnome (or if you use a dock as plank on other DE)

**Comment by gizmocodes** [comment]
What DE are you using Kuch?

**Comment by bilelmoussaoui** [comment]
Gnome on Arch

**Comment by gizmocodes** [comment]
Odd; I remember getting the same problem as bil, but on a Fedora derivative. Also with GNOME.

**Comment by bilelmoussaoui** [comment]
Try using ALT+TAB on  Gnome and you will see it :) (or on other DE too)

**Comment by gizmocodes** [comment]
Would if I could; unfortunately (Since I dual-boot), an update to Winderp screwed over my Linux partition. So ATM I'm stuck on Winderp.

**Comment by Kuchiriel** [comment]
Download and update the application.

Now we have a file in /opt/skype_unofficial_client/  called "skype.html".

Put a html title tag and see if it changes something.

**Comment by bilelmoussaoui** [comment]
Sadly, it's still the same thing :(

**Comment by Kuchiriel** [comment]
:(
Hope node.js people fix it soon. Anything reopen the issue.
