### ISSUE TITLE
Use cookies

### ISSUE THREAD

**Issue by bilelmoussaoui** [haskellcamargo/skype-unofficial-client#3]
Please use cookies to save my session

**Comment by ryanwarsaw** [comment]
This would be super handy, I'm not really knowledgeable in this area, but I'd love to take a look and try to do this over the weekend.

**Comment by Kuchiriel** [comment]
I will do some reading about it, sounds simple.

**Comment by haskellcamargo** [comment]
This has been already implemented. The client is already supporting cookies and Skype has added a "Keep me connected" checkbox on the login screen. Session management is already working.
