### ISSUE TITLE
Adaptation for when in mobile devices

### ISSUE THREAD

**Issue by danimesq** [haskellcamargo/skype-unofficial-client#33]

**Comment by gizmocodes** [comment]
Umm, theres a thing called Skype for Android and Skype for iOS.

**Comment by danimesq** [comment]
@GizmoCodes and for Tizen & Firefox OS?

**Comment by gizmocodes** [comment]
Tizen is an Android distro; hence its compatible. Firefox OS? I didn't even know that was still available.

**Comment by gizmocodes** [comment]
And besides, Tizen is for Samsung Gear watches primarily; I'm pretty sure that Tizen has a thing called Gear Store; If Skype wasn't on that, then I would imagine Samsung would be smokin' something.

**Comment by danimesq** [comment]
Umm, theres a thing called "other powerfull HTML5 operating systems borning because HTML5 is the future".
And Firefox OS is used by a lot of poor people.
Theres a thing called "Skype for Windows", but the developer of this repo is preparing to launch it for Windows users test. Why not test it in Firefox OS or Firefox iOS/Android?

**Comment by gizmocodes** [comment]
Welp, I'd ask haskellcamargo then.

**Comment by Kuchiriel** [comment]
Could you be more specific?
