### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by danimesq** [haskellcamargo/skype-unofficial-client#34]
Can run from web in haskellcamargo.github.io/skype-unofficial-client.

**Comment by gizmocodes** [comment]
Just go to web.skype.com. If you mean you want to use Skype from haskell's GH site, then.... why?

**Comment by danimesq** [comment]
This repo is based on Skype Web?

**Comment by gizmocodes** [comment]
Its a wrapper, it the simplist form.
