### ISSUE TITLE
Support Mac OS X

### ISSUE THREAD

**Issue by danimesq** [haskellcamargo/skype-unofficial-client#35]

**Comment by gizmocodes** [comment]
Whats wrong with the Mac OSX version from Microsoft? And again, this is a wrapper; if you want this client on Mac already you can basically just go to web.skype.com.

**Comment by Kuchiriel** [comment]
Before this feature isn't added, you can [build for your OSX](https://github.com/nwjs/nw.js/wiki/Application-auto-building-scripts-for-Linux-Windows-and-OSX).
