### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [haskellcamargo/skype-unofficial-client#36]
.

**Comment by gizmocodes** [comment]
I sent a letter to haskell awhile back. My idea for doing this is adding in the parts of Chromium that do plugins and stuff and building that in, and then installing the Skype call plugin on the plugin API thingy. No idea if that'd work, but it might.

However, the main reason I believe that he hasn't been able to add call support is, since this is Microsoft we're talking about, legal issues. Microsoft is _very_ iffy when it comes to these things. So I'm not sure yet. The tray thing shouldn't be _that_ hard, but its probably a lower priority for haskell.

**Comment by ItsiAdam** [comment]
I don't know much of anything about this, but theoretically theres nothing that M$ can do about it, they can't stop you from running essentially a stripped down version of an open source browser with their public addon.

**Comment by gizmocodes** [comment]
Yes, but including the Skype for Web plugin with the client would give them grounds. And the plugin is kinda needed for calls.

**Comment by AfterRebelion** [comment]
Then don't add the plugin. Instead, add the plugins subsystem, and on the first start of the application, use a pop-up to send people to download the plugin.
..or wait until they adopt WebRTC.
  --(translated with Yandex from Spanish)

**Comment by AfterRebelion** [comment]
Forget what I said, it appears that the [Chrome Extension](https://chrome.google.com/webstore/detail/skype-calling/blakpkgjpemejpbmfiglncklihnhjkij) is [unsupported on Linux](http://community.skype.com/t5/Skype-for-Web-Beta/Can-t-install-Skype-Calling-extension-for-Chrome-on-Linux/m-p/4010883/highlight/true#M252). I tried to install it, first from the Chrome Store (That gave me a stupid error with img/icon-32.png) and then with [a repackaged version with that error fixed](http://community.skype.com/t5/Skype-for-Web-Beta/Can-t-install-Skype-Calling-extension-for-Chrome-on-Linux/m-p/4276330/highlight/true#M1765) (http://goo.gl/lMUqSN), but even after cheaten Skype web to think that I was on Windows with a modified User-Agent, it did nothing when I tried to make a call.
So the only option left is the second one, wait until they move the web to WebRTC.

**Comment by AlvarOsO** [comment]
[There is now an official linux plugin!](http://community.skype.com/t5/Skype-for-Web-Beta/Skype-Web-Linux-plugin-is-now-avaliable/td-p/4307133)

**Comment by ItsiAdam** [comment]
The user could even download it themself, thats semi legal

**Comment by gizmocodes** [comment]
Download what themselves? The plugin? As Alvar said, the Skype plugin doesn't work Linux, even with a modified User-Agent (Trust me, I tried too).

**Comment by ItsiAdam** [comment]
Yeah, the plugin. If the plugin ever becomes functional, to keep it legal instead of packaging it with the program the client should be prompted in the installation to go download and install it theirself.

**Comment by ebkalderon** [comment]
@gizmocodes The current Skype Web UI seems to use plain HTML5 for audio calling which should work in all browsers, but Microsoft has only tested it on Edge. As a workaround, open the `package.json` file (for Arch users with the AUR package, this should be in `/opt/skype_unofficial_client`) and replace the user agent with:

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586
```

After restarting the app, you should be able to call the "Echo/Sound Test Service" fine.
