### ISSUE TITLE
What is the point? Why not just "Add to Desktop" ?

### ISSUE THREAD

**Issue by schoening** [haskellcamargo/skype-unofficial-client#37]
I tried it out and.. well.. why not just do a borderless window by adding it to the desktop via chrome? Seems like a lot of extra work for the same end result. Or am I missing something :o

**Comment by hmlendea** [comment]
Well, for one, I prefer not to rely on Chrome for my apps, when possible. Also, many people use Firefox and AFAIK it's not possible there.
Another reason is that, eventually, this application can be improved beyond the web apps' features, if the author so desires, just like the Unofficial Facebook Messenger desktop client, which started as a wrapper too.
What I would like to see from this project is full integration with my DE: notifications, tray icon, maybe a chat menu integration for Ubuntu Unity users... things like that, which you can't do by using the Chrome app.

**Comment by schoening** [comment]
Thanks for the answer :)

I didn't think of things like tray icons when I posted it. 

Cheers!
