### ISSUE TITLE
segfault every start of application in Manjaro

### ISSUE THREAD

**Issue by giamat86** [haskellcamargo/skype-unofficial-client#40]
Good morning,
I've been downloaded skype-destkop-bin from yaourt (manjaro).
Every time I launch the app, it closes automatically and in dmesg shows this error (or similar):
"segfault at 7fff0de31f18 ip 000055adede8450a sp 00007fff0de31f20 error 6 in skype[55adede70000+27000]".

Same problem if I clone the repository and I compile the sources (the compile goes all ok).

**Comment by Kuchiriel** [comment]
You have tested it in other distros?

**Comment by giamat86** [comment]
I don't nave time to install another distros because PC isn't mine. Next week I will install ubuntu and I'll test it..

**Comment by giamat86** [comment]
I've tried in Ubuntu unity x64 and all works fine, I think the problem is something in cinnamon preinstalled in my manjaro distro. (Developed by community). I don't know if in linux mint works or not.

**Comment by giamat86** [comment]
It seems that the segfault was in libfreetype.so.6.12.3 (manjaro latest version)
I also tried other DE (thinking that the problem was cinnamon) but without success.. :(

**Comment by giamat86** [comment]
I've found a little workaround:
with yaourt I have installed freetype2-cleartype-2.5.5-1 and I've removed freetype2-2.6.3-1 and the client works!
I don't know if the freetype2 package is need for other applications (not installed by pacman or yaourt) but for now seems all ok!

**Comment by gizmocodes** [comment]
Manjaro is an Arch distribution, is it not? I'm using Arch with Freetype 2.6.3-1 and it works fine (Aside from calls, but thats Microsoft's fault).

**Comment by giamat86** [comment]
Yes is an Arch Linux distribution, I don't know why forma me doesn't works with Freetype 2.6.3-1.. Today I try to reinstall this package and I relaunch the client.

**Comment by giamat86** [comment]
Nothing to do.. skype-unofficial-client in my manjaro x64 with freetype2 (2.6.3-1) package doesn't works. Now I can't install freetype2-cleartype because there is a conflict of dependence with last updates.. :(
