### ISSUE TITLE
Icon and .desktop not working with Plasma 5

### ISSUE THREAD

**Issue by ghost** [haskellcamargo/skype-unofficial-client#51]
Hello,
with Ubuntu it seemed to work fine but when running on Arch/Plasma5 (from AUR) it will display the icon in the tray with a black background and the launcher with no icon at all.
Also when I try to start it via the startmenu I get this:

> KDEInit could not launch '/tmp/yaourt-tmp-hering/aur-skype-desktop-bin/pkg/skype-desktop-bin/opt/skype_unofficial_client/skype'

Edit: Running from console I get:

> /usr/bin/skype-desktop: Line 2: cd: /tmp/yaourt-tmp-hering/aur-skype-desktop-bin/pkg/skype-desktop-bin/opt/skype_unofficial_client: File or Directory not found
> /usr/bin/skype-desktop: Line 3: ./skype: File or Directory not found

**Comment by HighIO** [comment]
It looks like ${pkgdir} didn't point`/opt/skype_skype_unofficial_client` folder correctly.
You should re-do `/usr/bin/skype-desktop` and `/usr/share/applications/skype-desktop.desktop`
Delete all `/tmp/yaourt-tmp-hering/aur-skype-desktop-bin/pkg/skype-desktop-bin/`

**Comment by Kuchiriel** [comment]
@HighIO, please, if you have time, send a PR with the modified $(pkgdir).
