### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by renat2985** [haskellcamargo/skype-unofficial-client#52]
The program does not spell check. Please make.

**Comment by gizmocodes** [comment]
I lik no spelchek cauz then i can perpusly type badly lik dis.

(Please note: I don't actually type like above.)

**Comment by Kuchiriel** [comment]
It should be optional, if you want, put this argument in /usr/share/applications/skype-desktop.desktop.

--enable-spell-checking

Its a good idea creating some kind of hotkey to enable it?

**Comment by Kuchiriel** [comment]
Some has already done. '-'

Check makefile, you will find this.

I will close the issue.

> echo "Exec=$(PREFIX)/opt/skype_unofficial_client/skype --enable-spell-checking %U" >> $(PREFIX)$(SHARE_APPS_FILE)
