### ISSUE TITLE
How can I uninstall this version?

### ISSUE THREAD

**Issue by truongnguyen1912** [haskellcamargo/skype-unofficial-client#57]
Hi,

Microsoft has released Skype for Linux alpha, so I think I can switch to that version.
But i don't know how to uninstall this version.
I'm currently on ElementaryOS Freya.

Thank you for your awesome work!

**Comment by Kuchiriel** [comment]
If you installed with pacman, just pacman -Rns skype-desktop-bin. 

If you don't, just:
rm -rf /opt/skype_unofficial_client
rm /usr/bin/skype-desktop
rm /usr/share/applications/skype-desktop.desktop
