### ISSUE TITLE
Fonts problem in Debian Buster LXDE

### ISSUE THREAD

**Issue by usernatilds** [haskellcamargo/skype-unofficial-client#66]
See
When send file:
![send file](https://user-images.githubusercontent.com/25496130/30709372-60e1990a-9ed8-11e7-86dc-821609ccc17e.png)
Or in tray icon:
![tray](https://user-images.githubusercontent.com/25496130/30709375-61251f2c-9ed8-11e7-810b-44c4818cc3ea.png)

And is possible change lenguage? My lenguage back for english.

**Comment by onlurking** [comment]
Hi @usernatilds!
Well, we don't maintain this project anymore, you should look the [ghetto-skype](https://github.com/stanfieldr/ghetto-skype) client instead.

**Comment by usernatilds** [comment]
@onlurking ok, how to uninstall skype-unoffial-client?

**Comment by onlurking** [comment]
@usernatilds, you installed though "make install"? 
If so you can uninstall it manually by running
```bash
rm -rf /opt/skype_unofficial_client
rm /usr/share/applications/skype-desktop.desktop
rm /usr/bin/skype-desktop
```

**Comment by usernatilds** [comment]
@onlurking, thanks.

**Comment by usernatilds** [comment]
I now see skype preview for linux, microsoft in the future make a same version of windows of skype in linux.
https://go.skype.com/skypeforlinux-64-preview.deb

I'm use skype preview version 8.7.76.58287, is good.

Skype now use Electron for porting skype in all platforms with all features, good.
