### ISSUE TITLE
No skype icon in task bar

### ISSUE THREAD

**Issue by probil** [haskellcamargo/skype-unofficial-client#7]
http://i.imgur.com/mhiLNoX.jpg
No skype icon in task bar, so it's hard to recognize it.

**Comment by ghost** [comment]
I do see the Skype icon in Cinnamon 2.6.13.

**Comment by ryanwarsaw** [comment]
I also can't see the Skype icon in the task bar, I'm using Cinnamon 2.6.13, default setup for Antergos.

**Comment by weini37** [comment]
Xfce4 - not working

**Comment by Israphel** [comment]
+1, no icon in kde either. Also a systray icon would be useful

**Comment by Similacrest** [comment]
xfce4 - no icon and I can't even configure kdocker for it.

**Comment by hmlendea** [comment]
Gnome Shell 3.18.3 has the same problem. It displays the default/unkown/other icon and the name "Unknown"
It is caused by the window not having a WM_CLASS set. If I use xdotool to set it then the icon works and the name is correct

**Comment by Kuchiriel** [comment]
Guys, icon problem was solved for kde, gnome-shell and xfce4? Cinnamon still fine?

**Comment by Kuchiriel** [comment]
Well, seems everything is okay now. Anything reopen the issue.

**Comment by Israphel** [comment]
What about the systray icon?

**Comment by hmlendea** [comment]
On GNOME 3.18.3 my dash shows the hardcoded icon (instead the one from my icon theme) and the name is "chromium-browser"
EDIT: Solved by appending StartupWMClass=crx_monljlleikpphbhopghghdbggidfahha to /usr/share/applications/skype-desktop.desktop (I've got the WM_CLASS by running 'xprop' and clicking on the Skype window, in case anyone wonders)

**Comment by Similacrest** [comment]
XFCE4 - no systray

**Comment by Kuchiriel** [comment]
@Hori873 I will update the .desktop file. @ShareDVI its up to @haskellcamargo to take a look at the binaries, running from nw.js works.
