### ISSUE TITLE
New "video-smiles" is not playing

### ISSUE THREAD

**Issue by probil** [haskellcamargo/skype-unofficial-client#8]
![screenshot](http://i.imgur.com/YJYWkTq.png)

This is a **video**.

[Link to simple "video-smile"](https://static-asm.secure.skypeassets.com/pes/v1/items/0b9704a393a846ea845821cc8eea157f/views/default)

It seems like `libffmpegsumo.so` need to be distributed with Node-WebKit. 
### Official docs

[Using MP3 & MP4 (H.264) using the video & audio tags.](https://github.com/nwjs/nw.js/wiki/Using-MP3-%26-MP4-%28H.264%29-using-the--video--%26--audio--tags.)

**Comment by Kuchiriel** [comment]
My Skype is "trevorkuchiriel", add me there, and send me some video-smile please, i will try to fix it.

**Comment by Kuchiriel** [comment]
Can you reinstall and confirm if the bug persists?
