### ISSUE TITLE
Binaries outside the repository

### ISSUE THREAD

**Issue by ghost** [haskellcamargo/skype-unofficial-client#9]
What do you think about taking the binaries out of the repo, include information about where to get (or how to build) them in the `README` and, eventually, package the code + binaries as releases?

The client works like a charm, thanks for it!

**Comment by darealshinji** [comment]
A quick way of getting the binaries is using npm. Install with `npm install nwjs` and the binaries will be inside `node_modules/nw/nwjs`.

**Comment by Kuchiriel** [comment]
To build out of /src directory just follow nw.js guide.
https://github.com/nwjs/nw.js/wiki/how-to-package-and-distribute-your-apps

We use a precompiled binary to make installation faster.

When i have some time, i will do some standardization, to build it from source, then add a new package in AUR (skype-desktop-git).

This is the same technology behind popcorn-time, and popcorn-time use a git repository to both binary and source, just the distribution method that changes. AUR is one example. Anything reopen the issue.
